query AllAbouts($first: IntType = 100, $skip: IntType = 0, $yearId: ItemId, $locale: SiteLocale) {
	abouts: allAbouts(
		filter: { year: { eq: $yearId } }
		locale: $locale
		fallbackLocales: [sv]
		first: $first
		skip: $skip
	) {
		...AboutFragmentLight
	}
	pagination: _allAboutsMeta {
		count
	}
}

query About($slug: String!, $locale: SiteLocale) {
	about(filter: { slug: { eq: $slug } }, locale: $locale, fallbackLocales: [sv]) {
		...AboutFragment
	}
}

query MainAbout($yearId: ItemId, $locale: SiteLocale) {
	abouts: allAbouts(
		filter: { OR: [{ year: { eq: $yearId } }, { year: { exists: false } }] }
		first: 1
		locale: $locale
		fallbackLocales: [sv]
	) {
		...AboutFragment
	}
}

query AllAboutsMenu($locale: SiteLocale) {
	abouts: allAbouts(locale: $locale, fallbackLocales: [sv], first: 100) {
		title
		slug
	}
}
