query AllAbouts($first: IntType = 100, $skip: IntType = 0, $yearId: ItemId, $locale: SiteLocale) {
	allAbouts(
		filter: { year: { eq: $yearId }, slug: { neq: null } }
		locale: $locale
		first: $first
		skip: $skip
	) {
		...AboutFragmentLight
	}
	_allAboutsMeta(filter: { year: { eq: $yearId }, slug: { neq: null } }) {
		count
	}
}

query About($slug: String!, $locale: SiteLocale) {
	about(filter: { slug: { eq: $slug } }, locale: $locale, fallbackLocales: [sv]) {
		...AboutFragment
	}
}

query MainAbout($yearId: ItemId, $locale: SiteLocale) {
	allAbouts(
		filter: { OR: [{ year: { eq: $yearId } }, { year: { exists: false } }] }
		first: 1
		locale: $locale
		fallbackLocales: [sv]
	) {
		...AboutFragment
	}
}

query AllAboutsMenu($locale: SiteLocale) {
	allAbouts(locale: $locale, fallbackLocales: [sv], first: 100) {
		title
		slug
	}
}

fragment AboutFragment on AboutRecord {
	__typename
	_modelApiKey
	id
	title
	intro
	slug
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	year {
		...YearFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on ExhibitionRecord {
								id
								slug
								title
							}
							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_allSlugLocales {
		locale
		value
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment AboutFragmentLight on AboutRecord {
	__typename
	id
	title
	intro
	slug
	image {
		...ImageThumbnailFragment
	}
	year {
		...YearFragment
	}
}
