query AllExhibitions($locale: SiteLocale, $yearId: ItemId) {
	exhibitions: allExhibitions(filter: { year: { eq: $yearId } }, locale: $locale, first: 100) {
		...ExhibitionFragmentLight
	}
	pagination: _allExhibitionsMeta(locale: $locale) {
		count
	}
}

query Exhibition($slug: String!, $locale: SiteLocale) {
	exhibition(filter: { slug: { eq: $slug } }, locale: $locale) {
		...ExhibitionFragment
	}
}
