query AllLocations(
	$first: IntType = 100
	$skip: IntType = 0
	$locale: SiteLocale
	$yearId: ItemId
) {
	allLocations(
		filter: { year: { eq: $yearId }, slug: { neq: null } }
		first: $first
		skip: $skip
		orderBy: [title_ASC]
		locale: $locale
	) {
		...LocationFragmentLight
	}

	_allLocationsMeta(locale: $locale, filter: { year: { eq: $yearId }, slug: { neq: null } }) {
		count
	}
}

query Location($slug: String!, $locale: SiteLocale, $yearId: ItemId) {
	location(
		filter: { slug: { eq: $slug }, year: { eq: $yearId } }
		locale: $locale
		fallbackLocales: [sv]
	) {
		id
		title
		city
		address
		image {
			...ImageFragment
		}
		intro(markdown: false)
		webpage
		slug
		_allReferencingExhibitions(first: 100, filter: { year: { eq: $yearId } }) {
			...ExhibitionFragmentLight
		}
		_allReferencingPrograms(first: 100, filter: { year: { eq: $yearId } }) {
			...ProgramFragmentLight
		}
		content {
			value
			blocks {
				__typename
				... on ImageRecord {
					__typename
					id
					layout
					image {
						...ImageFragment
					}
				}
				... on ImageGalleryRecord {
					__typename
					id
					images {
						...ImageThumbnailFragment
					}
				}
				... on LinkButtonRecord {
					__typename
					id
					link {
						__typename
						... on ExternalLinkRecord {
							__typename
							id
							title
							url
						}
						... on InternalLinkRecord {
							__typename
							id
							record {
								... on AboutRecord {
									id
									slug
									title
								}
								... on ExhibitionRecord {
									id
									slug
									title
								}
								... on LocationRecord {
									id
									slug
									title
								}
								... on NewsRecord {
									id
									slug
									title
								}
								... on ParticipantRecord {
									id
									slug
									name
								}
								... on ProgramRecord {
									id
									slug
									title
								}
							}
						}
					}
				}
				... on VideoRecord {
					__typename
					id
					title
					video {
						height
						width
						title
						provider
						providerUid
						thumbnailUrl
						url
					}
				}
				... on RecordInterface {
					__typename
					id
				}
			}
		}
		_allSlugLocales {
			locale
			value
		}
		_seoMetaTags {
			...SeoMetaTagsFragment
		}
	}
}

fragment LocationFragment on LocationRecord {
	id
	title
	city
	address
	image {
		...ImageFragment
	}
	intro(markdown: false)
	webpage
	slug
	exhibitions: _allReferencingExhibitions(first: 100) {
		...ExhibitionFragmentLight
	}
	programs: _allReferencingPrograms(first: 100) {
		...ProgramFragmentLight
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on ExhibitionRecord {
								id
								slug
								title
							}
							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_allSlugLocales {
		locale
		value
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment LocationFragmentLight on LocationRecord {
	id
	title
	city
	address
	intro(markdown: false)
	webpage
	slug
	image {
		...ImageThumbnailFragment
	}
	year {
		id
		title
	}
}
