query AllLocations(
	$first: IntType = 100
	$skip: IntType = 0
	$locale: SiteLocale
	$yearId: ItemId
) {
	locations: allLocations(
		filter: { year: { eq: $yearId } }
		first: $first
		skip: $skip
		orderBy: [title_ASC]
		locale: $locale
	) {
		...LocationFragmentLight
	}

	pagination: _allLocationsMeta(locale: $locale) {
		count
	}
}

query Location($slug: String!, $locale: SiteLocale, $yearId: ItemId) {
	location(
		filter: { slug: { eq: $slug }, year: { eq: $yearId } }
		locale: $locale
		fallbackLocales: [sv]
	) {
		id
		title
		city
		address
		image {
			...ImageFragment
		}
		intro(markdown: false)
		webpage
		slug
		exhibitions: _allReferencingExhibitions(first: 100, filter: { year: { eq: $yearId } }) {
			...ExhibitionFragmentLight
		}
		programs: _allReferencingPrograms(first: 100, filter: { year: { eq: $yearId } }) {
			...ProgramFragmentLight
		}
		content {
			value
			blocks {
				__typename
				... on ImageRecord {
					__typename
					id
					layout
					image {
						...ImageFragment
					}
				}
				... on ImageGalleryRecord {
					__typename
					id
					images {
						...ImageThumbnailFragment
					}
				}
				... on LinkButtonRecord {
					__typename
					id
					link {
						__typename
						... on ExternalLinkRecord {
							__typename
							id
							title
							url
						}
						... on InternalLinkRecord {
							__typename
							id
							record {
								... on AboutRecord {
									id
									slug
									title
								}
								... on ExhibitionRecord {
									id
									slug
									title
								}
								... on LocationRecord {
									id
									slug
									title
								}
								... on NewsRecord {
									id
									slug
									title
								}
								... on ParticipantRecord {
									id
									slug
									name
								}
								... on ProgramRecord {
									id
									slug
									title
								}
							}
						}
					}
				}
				... on VideoRecord {
					__typename
					id
					title
					video {
						height
						width
						title
						provider
						providerUid
						thumbnailUrl
						url
					}
				}
				... on RecordInterface {
					__typename
					id
				}
			}
		}
		_allSlugLocales {
			locale
			value
		}
		_seoMetaTags {
			...SeoMetaTagsFragment
		}
	}
}
