query AllLocations(
	$first: IntType = 100
	$skip: IntType = 0
	$locale: SiteLocale
	$yearId: ItemId
) {
	locations: allLocations(
		filter: { year: { eq: $yearId } }
		first: $first
		skip: $skip
		orderBy: [_createdAt_DESC]
		locale: $locale
	) {
		...LocationFragmentLight
	}

	pagination: _allLocationsMeta(locale: $locale) {
		count
	}
}

query Location($slug: String!, $locale: SiteLocale) {
	location(filter: { slug: { eq: $slug } }, locale: $locale) {
		...LocationFragment
	}
}
