query AllNews($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale) {
	allNews(
		locale: $locale
		fallbackLocales: [sv]
		first: $first
		skip: $skip
		orderBy: [_createdAt_DESC]
	) {
		...NewsFragmentLight
	}

	_allNewsMeta(locale: $locale) {
		count
	}
}

query News($slug: String!, $locale: SiteLocale) {
	news(filter: { slug: { eq: $slug } }, locale: $locale) {
		...NewsFragment
	}
}

fragment NewsFragment on NewsRecord {
	id
	title
	intro(markdown: false)
	image {
		...ImageFragment
	}
	slug
	_createdAt
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							__typename
							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
								_year: year {
									id
									title
								}
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
								year {
									id
									title
								}
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
								year {
									id
									title
								}
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
								year {
									id
									title
								}
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
								year {
									id
									title
								}
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
	_allSlugLocales {
		locale
		value
	}
}

fragment NewsFragmentLight on NewsRecord {
	id
	title
	intro(markdown: false)
	slug
	image {
		...ImageThumbnailFragment
	}
	_createdAt
}
