query AllNews($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale) {
	news: allNews(
		locale: $locale
		fallbackLocales: [sv]
		first: $first
		skip: $skip
		orderBy: [_createdAt_DESC]
	) {
		...NewsFragmentLight
	}

	pagination: _allNewsMeta(locale: $locale, fallbackLocales: [sv]) {
		count
	}
}

query News($slug: String!, $locale: SiteLocale) {
	news(filter: { slug: { eq: $slug } }, locale: $locale, fallbackLocales: [sv]) {
		...NewsFragment
	}
}
