query AllPartners($locale: SiteLocale, $yearId: ItemId) {
	partners: allPartners(filter: { year: { eq: $yearId } }, first: 100) {
		...PartnerFragmentLight
	}
	pagination: _allPartnersMeta {
		count
	}
}

query Partner($slug: String!, $locale: SiteLocale) {
	partner(filter: { slug: { eq: $slug } }) {
		...PartnerFragment
	}
}
