query AllPartners($locale: SiteLocale, $yearId: ItemId) {
	allPartners(
		filter: { year: { eq: $yearId }, slug: { neq: null } }
		locale: $locale

		first: 100
	) {
		...PartnerFragmentLight
	}
	_allPartnersMeta(filter: { year: { eq: $yearId }, slug: { neq: null } }) {
		count
	}
}

query Partner($slug: String!, $locale: SiteLocale) {
	partner(filter: { slug: { eq: $slug } }, locale: $locale, fallbackLocales: [sv]) {
		...PartnerFragment
	}
}

fragment PartnerFragment on PartnerRecord {
	_createdAt
	id
	title
	intro(markdown: false)
	slug
	image {
		...ImageFragment
	}
	year {
		...YearFragment
	}

	address
	city
	webpage
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							__typename
							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
								_year: year {
									id
									title
								}
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
								year {
									id
									title
								}
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
								year {
									id
									title
								}
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
								year {
									id
									title
								}
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
								year {
									id
									title
								}
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_allSlugLocales {
		locale
		value
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment PartnerFragmentLight on PartnerRecord {
	id
	title
	intro(markdown: false)
	image {
		...ImageThumbnailFragment
	}
	year {
		...YearFragmentLight
	}
	slug
}
