query AllPrograms($locale: SiteLocale, $yearId: ItemId) {
	allPrograms(
		filter: { year: { eq: $yearId } }
		locale: $locale
		fallbackLocales: [sv]
		orderBy: [startDate_ASC, startTime_ASC]
		first: 100
	) {
		...ProgramFragmentLight
	}
	_allProgramsMeta(locale: $locale, filter: { year: { eq: $yearId } }) {
		count
	}
}

query Program($slug: String!, $locale: SiteLocale) {
	program(filter: { slug: { eq: $slug } }, locale: $locale, fallbackLocales: [sv]) {
		...ProgramFragment
	}
}

query AllProgramCategories($locale: SiteLocale) {
	allProgramCategories(locale: $locale, orderBy: title_DESC, first: 100) {
		id
		title
		desc
	}
}

fragment ProgramFragment on ProgramRecord {
	__typename
	_modelApiKey
	id
	title
	startDate
	endDate
	time
	address
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	misc
	location {
		...LocationFragmentLight
	}
	partipants {
		...ParticipantFragmentLight
	}
	partner {
		...PartnerFragmentLight
	}
	programCategory {
		id
		title
	}
	slug
	externalLink
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on ExhibitionRecord {
								id
								slug
								title
							}
							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_allSlugLocales {
		locale
		value
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment ProgramFragmentLight on ProgramRecord {
	__typename
	_modelApiKey
	id
	title
	startDate
	endDate
	intro(markdown: false)
	time
	image {
		...ImageThumbnailFragment
	}
	programCategory {
		id
		title
	}
	year {
		...YearFragmentLight
	}
	slug
}
