query Start($locale: SiteLocale) {
	start(locale: $locale, fallbackLocales: [sv]) {
		id
		content {
			__typename
			... on StartTextRecord {
				__typename
				id
				headline
				text
				link {
					__typename
					... on ExternalLinkRecord {
						_modelApiKey
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						_modelApiKey
						id
						internalTitle: title
						record {
							__typename

							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
							}
						}
					}
				}
			}
			... on StartNewsRecord {
				__typename
				id
				amount
			}
			... on StartVideoRecord {
				__typename
				id
				title
				video {
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on StartProgramRecord {
				__typename
				id
				amount
			}
			... on StartFullscreenImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				headline
				text
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						_modelApiKey
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						_modelApiKey
						id
						record {
							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
							}
						}
					}
				}
			}
			... on StartFullscreenVideoRecord {
				__typename
				id
				headline
				text(markdown: false)
				video {
					...VideoFragment
				}
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						_modelApiKey
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						_modelApiKey
						id
						internalTitle: title
						record {
							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
							}
						}
					}
				}
			}

			... on StartRandomParticipantRecord {
				__typename
				id
				amount
			}
			... on StartExhibitionRecord {
				__typename
				id
				amount
			}

			... on StartFullscreenImageRecord {
				id
				image {
					...ImageFragment
				}
			}
			... on StartFullBleedImageRecord {
				id
				image {
					...ImageFragment
				}
				headline
				text
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						_modelApiKey
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
							}
						}
					}
				}
			}
			... on StartSelectedLocationRecord {
				__typename
				id
				locations {
					...LocationFragmentLight
				}
			}
			... on StartGalleryRecord {
				__typename
				id
				headline
				images {
					...ImageFragment
				}
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						_modelApiKey
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ExhibitionRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on LocationRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on NewsRecord {
								_modelApiKey
								id
								slug
								title
							}
							... on ParticipantRecord {
								_modelApiKey
								id
								slug
								name
							}
							... on ProgramRecord {
								_modelApiKey
								id
								slug
								title
							}
						}
					}
				}
			}
		}
	}
}

query StartData(
	$newsItems: IntType
	$programItems: IntType
	$date: Date
	$yearId: ItemId
	$locale: SiteLocale
) {
	allNews(
		locale: $locale
		first: $newsItems
		orderBy: _createdAt_DESC
		filter: { slug: { neq: null } }
	) {
		...NewsFragmentLight
	}
	allPrograms(
		filter: { startDate: { gte: $date }, year: { eq: $yearId }, slug: { neq: null } }
		locale: $locale
		fallbackLocales: [sv]
		first: $programItems
		orderBy: startDate_DESC
	) {
		...ProgramFragmentLight
	}
	allParticipants(
		filter: { year: { eq: $yearId }, slug: { neq: null } }
		first: 100
		orderBy: _createdAt_DESC
		locale: $locale
		fallbackLocales: [sv]
	) {
		...ParticipantFragmentLight
	}
}
