query AllYears($locale: SiteLocale, $year: String, $first: IntType, $skip: IntType) {
	allYears(
		filter: { title: { neq: $year } }
		first: $first
		skip: $skip
		locale: $locale
		fallbackLocales: [sv]
		orderBy: title_DESC
	) {
		...YearFragment
	}
	_allYearsMeta(locale: $locale, filter: { title: { neq: $year } }) {
		count
	}
}

query Year($title: String!, $locale: SiteLocale) {
	year(filter: { title: { eq: $title } }, locale: $locale, fallbackLocales: [sv]) {
		...YearFragment
	}
}

fragment YearFragment on YearRecord {
	__typename
	_modelApiKey
	id
	title
	slug
}

fragment YearFragmentLight on YearRecord {
	__typename
	_modelApiKey
	id
	title
	slug
}
