query AllYears($locale: SiteLocale, $year: String) {
	years: allYears(
		filter: { title: { neq: $year } }
		locale: $locale
		fallbackLocales: [sv]
		first: 100
		orderBy: title_DESC
	) {
		...YearFragment
	}
}

query Year($title: String!, $locale: SiteLocale) {
	year(filter: { title: { eq: $title } }, locale: $locale, fallbackLocales: [sv]) {
		...YearFragment
	}
}
