query AllYears($locale: SiteLocale, $year: String) {
	allYears(
		filter: { title: { neq: $year } }
		locale: $locale
		fallbackLocales: [sv]
		first: 100
		orderBy: title_DESC
	) {
		...YearFragment
	}
	_allYearsMeta(locale: $locale, filter: { title: { neq: $year } }) {
		count
	}
}

query Year($title: String!, $locale: SiteLocale) {
	year(filter: { title: { eq: $title } }, locale: $locale, fallbackLocales: [sv]) {
		...YearFragment
	}
}

fragment YearFragment on YearRecord {
	id
	title
	slug
}

fragment YearFragmentLight on YearRecord {
	id
	title
	slug
}
